
export const LOADING_VERSES = [
  { text: "The Lord is my shepherd; I shall not want.", reference: "Psalm 23:1" },
  { text: "For I know the plans I have for you, declares the Lord, plans for welfare and not for evil, to give you a future and a hope.", reference: "Jeremiah 29:11" },
  { text: "I can do all things through him who strengthens me.", reference: "Philippians 4:13" },
  { text: "Trust in the Lord with all your heart, and do not lean on your own understanding.", reference: "Proverbs 3:5" },
  { text: "And we know that for those who love God all things work together for good, for those who are called according to his purpose.", reference: "Romans 8:28" },
  { text: "But they who wait for the Lord shall renew their strength; they shall mount up with wings like eagles; they shall run and not be weary; they shall walk and not faint.", reference: "Isaiah 40:31" },
  { text: "Be strong and courageous. Do not be frightened, and do not be dismayed, for the Lord your God is with you wherever you go.", reference: "Joshua 1:9" },
  { text: "Give thanks to the Lord, for he is good, for his steadfast love endures forever.", reference: "Psalm 136:1" },
  { text: "The grass withers, the flower fades, but the word of our God will stand forever.", reference: "Isaiah 40:8" },
  { text: "Come to me, all who labor and are heavy laden, and I will give you rest.", reference: "Matthew 11:28" },
  { text: "Now faith is the assurance of things hoped for, the conviction of things not seen.", reference: "Hebrews 11:1" },
  { text: "Fear not, for I am with you; be not dismayed, for I am your God; I will strengthen you, I will help you, I will uphold you with my righteous right hand.", reference: "Isaiah 41:10" },
  { text: "But seek first the kingdom of God and his righteousness, and all these things will be added to you.", reference: "Matthew 6:33" },
  { text: "Peace I leave with you; my peace I give to you. Not as the world gives do I give to you. Let not your hearts be troubled, neither let them be afraid.", reference: "John 14:27" },
  { text: "Let all that you do be done in love.", reference: "1 Corinthians 16:14" },
  { text: "Be on your guard; stand firm in the faith; be courageous; be strong.", reference: "1 Corinthians 16:13" },
  { text: "May the God of hope fill you with all joy and peace in believing, so that by the power of the Holy Spirit you may abound in hope.", reference: "Romans 15:13" },
  { text: "God is our refuge and strength, a very present help in trouble.", reference: "Psalm 46:1" },
  { text: "The steadfast love of the Lord never ceases; his mercies never come to an end; they are new every morning; great is your faithfulness.", reference: "Lamentations 3:22-23" },
  { text: "For by grace you have been saved through faith. And this is not your own doing; it is the gift of God.", reference: "Ephesians 2:8" },
  { text: "And behold, I am with you always, to the end of the age.", reference: "Matthew 28:20" },
  { text: "But the fruit of the Spirit is love, joy, peace, patience, kindness, goodness, faithfulness, gentleness, self-control; against such things there is no law.", reference: "Galatians 5:22-23" },
  { text: "Commit your work to the Lord, and your plans will be established.", reference: "Proverbs 16:3" },
  { text: "Your word is a lamp to my feet and a light to my path.", reference: "Psalm 119:105" },
  { text: "Casting all your anxieties on him, because he cares for you.", reference: "1 Peter 5:7" },
  { text: "If any of you lacks wisdom, let him ask God, who gives generously to all without reproach, and it will be given him.", reference: "James 1:5" },
  { text: "Do not be anxious about anything, but in everything by prayer and supplication with thanksgiving let your requests be made known to God.", reference: "Philippians 4:6" },
  { text: "Whatever you do, work heartily, as for the Lord and not for men.", reference: "Colossians 3:23" },
  { text: "Do not be conformed to this world, but be transformed by the renewal of your mind.", reference: "Romans 12:2" },
  { text: "Oh, taste and see that the Lord is good! Blessed is the man who takes refuge in him!", reference: "Psalm 34:8" },
  { text: "For I am sure that neither death nor life... will be able to separate us from the love of God in Christ Jesus our Lord.", reference: "Romans 8:38-39" },
  { text: "For God gave us a spirit not of fear but of power and love and self-control.", reference: "2 Timothy 1:7" },
  { text: "He has told you, O man, what is good; and what does the Lord require of you but to do justice, and to love kindness, and to walk humbly with your God?", reference: "Micah 6:8" },
  { text: "Let the words of my mouth and the meditation of my heart be acceptable in your sight, O Lord, my rock and my redeemer.", reference: "Psalm 19:14" },
  { text: "The Lord your God is in your midst, a mighty one who will save; he will rejoice over you with gladness; he will quiet you by his love.", reference: "Zephaniah 3:17" },
  { text: "In all your ways acknowledge him, and he will make straight your paths.", reference: "Proverbs 3:6" },
  { text: "We love because he first loved us.", reference: "1 John 4:19" },
  { text: "I lift up my eyes to the hills. From where does my help come? My help comes from the Lord, who made heaven and earth.", reference: "Psalm 121:1-2" },
  { text: "Be joyful in hope, patient in affliction, faithful in prayer.", reference: "Romans 12:12" },
  { text: "Be still, and know that I am God.", reference: "Psalm 46:10" },
  { text: "The Lord is near to all who call on him, to all who call on him in truth.", reference: "Psalm 145:18" },
  { text: "He gives power to the faint, and to him who has no might he increases strength.", reference: "Isaiah 40:29" },
  { text: "Keep your heart with all vigilance, for from it flow the springs of life.", reference: "Proverbs 4:23" },
  { text: "Wait for the Lord; be strong, and let your heart take courage; wait for the Lord!", reference: "Psalm 27:14" },
  { text: "But the Lord is faithful. He will establish you and guard you against the evil one.", reference: "2 Thessalonians 3:3" },
  { text: "Let the peace of Christ rule in your hearts, to which indeed you were called in one body. And be thankful.", reference: "Colossians 3:15" },
  { text: "For the eyes of the Lord are on the righteous, and his ears are open to their prayer.", reference: "1 Peter 3:12" },
  { text: "Great is our Lord, and abundant in power; his understanding is beyond measure.", reference: "Psalm 147:5" },
  { text: "You keep him in perfect peace whose mind is stayed on you, because he trusts in you.", reference: "Isaiah 26:3" },
  { text: "The name of the Lord is a strong tower; the righteous man runs into it and is safe.", reference: "Proverbs 18:10" },
  { text: "But my God shall supply all your need according to his riches in glory by Christ Jesus.", reference: "Philippians 4:19" },
  { text: "I sought the Lord, and he answered me and delivered me from all my fears.", reference: "Psalm 34:4" },
  { text: "The Lord is my light and my salvation; whom shall I fear? The Lord is the stronghold of my life; of whom shall I be afraid?", reference: "Psalm 27:1" },
  { text: "Blessed is the man who remains steadfast under trial, for when he has stood the test he will receive the crown of life.", reference: "James 1:12" },
  { text: "The Lord will keep your going out and your coming in from this time forth and forevermore.", reference: "Psalm 121:8" },
  { text: "You are the light of the world. A city set on a hill cannot be hidden.", reference: "Matthew 5:14" },
  { text: "Rejoice always, pray without ceasing, give thanks in all circumstances.", reference: "1 Thessalonians 5:16-18" },
  { text: "But as for me and my house, we will serve the Lord.", reference: "Joshua 24:15" },
  { text: "Seek the Lord and his strength; seek his presence continually!", reference: "1 Chronicles 16:11" },
  { text: "Every word of God proves true; he is a shield to those who take refuge in him.", reference: "Proverbs 30:5" },
  { text: "Therefore do not be anxious about tomorrow, for tomorrow will be anxious for itself.", reference: "Matthew 6:34" },
  { text: "For where two or three are gathered in my name, there am I among them.", reference: "Matthew 18:20" },
  { text: "I am the way, and the truth, and the life. No one comes to the Father except through me.", reference: "John 14:6" },
  { text: "This is the day that the Lord has made; let us rejoice and be glad in it.", reference: "Psalm 118:24" },
  { text: "Greater love has no one than this, that someone lay down his life for his friends.", reference: "John 15:13" },
  { text: "But the Lord is with me as a dread warrior; therefore my persecutors will stumble.", reference: "Jeremiah 20:11" },
  { text: "Your word is a lamp to my feet and a light to my path.", reference: "Psalm 119:105" },
  { text: "Be kind to one another, tenderhearted, forgiving one another, as God in Christ forgave you.", reference: "Ephesians 4:32" },
  { text: "He restores my soul. He leads me in paths of righteousness for his name's sake.", reference: "Psalm 23:3" },
  { text: "Let your light shine before others, so that they may see your good works and give glory to your Father who is in heaven.", reference: "Matthew 5:16" },
  { text: "Ask, and it will be given to you; seek, and you will find; knock, and it will be opened to you.", reference: "Matthew 7:7" },
  { text: "For we walk by faith, not by sight.", reference: "2 Corinthians 5:7" },
  { text: "The righteous cry, and the Lord hears them; he delivers them from all their troubles.", reference: "Psalm 34:17" },
  { text: "Delight yourself in the Lord, and he will give you the desires of your heart.", reference: "Psalm 37:4" },
  { text: "Wait for the Lord; be strong and take heart and wait for the Lord.", reference: "Psalm 27:14" },
  { text: "My soul finds rest in God alone; my salvation comes from him.", reference: "Psalm 62:1" },
  { text: "Great is the Lord and most worthy of praise; his greatness no one can fathom.", reference: "Psalm 145:3" },
  { text: "I have hidden your word in my heart that I might not sin against you.", reference: "Psalm 119:11" },
  { text: "God is our refuge and strength, an ever-present help in trouble.", reference: "Psalm 46:1" },
  { text: "You guide me with your counsel, and afterward you will take me into glory.", reference: "Psalm 73:24" },
  { text: "Whatever you do, work at it with all your heart, as working for the Lord.", reference: "Colossians 3:23" }
];
