"use client";

import { useMemo } from 'react';
import type { FormDefinition, FormResponse, FormAnswerValue } from '@/types/forms';
import { Button } from '@/components/ui/button';

function stringifyValue(v: FormAnswerValue | undefined): string {
  if (typeof v === 'string') return v;
  if (Array.isArray(v)) return v.join(', ');
  return '';
}

export default function ReportPanel({
  form,
  response,
}: {
  form: FormDefinition;
  response: FormResponse;
}) {
  const fields = useMemo(() => [...form.fields].sort((a, b) => a.order - b.order), [form.fields]);

  const csvFileName = useMemo(() => {
    const title = form.title.replace(/[^a-z0-9]+/gi, '_').slice(0, 40) || 'form';
    return `report_${title}_${response.id}.csv`;
  }, [form.title, response.id]);

  const downloadCsv = () => {
    const header = ['field', 'value'];
    const lines: string[] = [];
    lines.push(header.join(','));

    lines.push(`submitter_email,"${response.submitterEmail.replace(/"/g, '""')}"`);

    for (const field of fields) {
      const raw = stringifyValue(response.answers?.[field.id] as any);
      const safe = String(raw).replace(/"/g, '""');
      lines.push(`"${field.label.replace(/"/g, '""')}","${safe}"`);
    }

    const csv = lines.join('\n');
    const blob = new Blob([csv], { type: 'text/csv;charset=utf-8' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = csvFileName;
    a.click();
    URL.revokeObjectURL(url);
  };

  const openPrintPdf = () => {
    const title = `Form report: ${form.title}`;
    const rowsHtml = fields
      .map((field) => {
        const value = stringifyValue(response.answers?.[field.id] as any);
        const safeLabel = field.label.replace(/</g, '&lt;').replace(/>/g, '&gt;');
        const safeValue = String(value).replace(/</g, '&lt;').replace(/>/g, '&gt;');
        return `<tr><td style="padding:6px;border:1px solid #ddd;font-size:12px;">${safeLabel}</td><td style="padding:6px;border:1px solid #ddd;font-size:12px;word-break:break-word;">${safeValue}</td></tr>`;
      })
      .join('');

    const html = `<!doctype html>
<html>
  <head>
    <meta charset="utf-8" />
    <title>${title}</title>
  </head>
  <body>
    <div style="padding:16px;font-family:sans-serif;">
      <h2 style="margin-top:0;">${title}</h2>
      <p style="color:#555;font-size:12px;margin-bottom:16px;"><b>Submitter email:</b> ${response.submitterEmail}</p>
      <table style="border-collapse:collapse;width:100%;table-layout:fixed;">
        ${rowsHtml}
      </table>
      <p style="color:#888;font-size:11px;margin-top:16px;">Generated by the admin UI.</p>
    </div>
  </body>
</html>`;

    const w = window.open('', '_blank', 'noopener,noreferrer,width=950,height=700');
    if (!w) return;
    w.document.open();
    w.document.write(html);
    w.document.close();
    w.focus();
    // User will choose "Save as PDF" in the print dialog.
    w.print();
  };

  return (
    <div className="space-y-3">
      <div className="flex flex-col sm:flex-row items-start sm:items-center justify-between gap-2">
        <div>
          <h3 className="text-section-title">{form.title} — Report</h3>
          <p className="text-sm text-muted-foreground">Submitter: {response.submitterEmail}</p>
        </div>
        <div className="flex gap-2">
          <Button variant="outline" onClick={downloadCsv}>
            CSV
          </Button>
          <Button onClick={openPrintPdf}>PDF</Button>
        </div>
      </div>

      <div className="overflow-x-auto">
        <table className="w-full text-[13px] border-collapse">
          <tbody>
            {fields.map((field) => (
              <tr key={field.id}>
                <td className="py-2 px-2 font-semibold border-b border-border/60" style={{ width: '36%' }}>
                  {field.label}
                </td>
                <td className="py-2 px-2 border-b border-border/60 break-words">
                  {stringifyValue(response.answers?.[field.id] as any) || <span className="text-muted-foreground">—</span>}
                </td>
              </tr>
            ))}
          </tbody>
        </table>
      </div>
    </div>
  );
}

